### ISSUE TITLE
Two functions have no return value            fgt.lib not found

### ISSUE THREAD

**Issue by Xi-Hsu** [miguelcastillon/fgt_threshold#1]
C4716	“fgt::Ifgt::compute_impl”: must return a value	Library-C++	d:\fgt_threshold-master\src\ifgt.cpp	260	

C4716	“fgt::Direct::compute_impl”: must return a valueLibrary-C++	d:\fgt_threshold-master\src\direct.cpp	48	
9>LINK : fatal error LNK1181: cannot open input file“..\Release\fgt.lib”
9>已完成生成项目“version.vcxproj”的操作 - 失败。
5>LINK : fatal error LNK1181: cannot open input file“..\Release\fgt.lib”
5>已完成生成项目“cluster.vcxproj”的操作 - 失败。
10>LINK : fatal error LNK1181: cannot open input file“..\Release\fgt.lib”
10>已完成生成项目“without_openmp.vcxproj”的操作 - 失败。
7>LINK : fatal error LNK1181: cannot open input file“..\Release\fgt.lib”
7>已完成生成项目“direct-tree.vcxproj”的操作 - 失败。
8>LINK : fatal error LNK1181: cannot open input file“..\Release\fgt.lib”
8>已完成生成项目“ifgt.vcxproj”的操作 - 失败。
6>LINK : fatal error LNK1181: cannot open input file“..\Release\fgt.lib”
6>已完成生成项目“direct.vcxproj”的操作 - 失败。
11>------ 已启动生成: 项目: ALL_BUILD, 配置: Release x64 ------
11>Building Custom Rule D:/fgt_threshold-master/CMakeLists.txt
11>CMake does not need to re-run because D:/fgt_threshold-master/build/CMakeFiles/generate.stamp is up-to-date.

**Comment by miguelcastillon** [comment]
Sorry, this package has only been tested on Ubuntu, I don't have experience compiling it on Windows.

Please let me know if you manage to solve this issue.

Thanks!

**Comment by Xi-Hsu** [comment]
Hello, I have solved this problem by recompiling googletest, but the bigger problem is that I now compile successfully lnrr, but, 2 point clouds of 10,000 orders of magnitude run 6 and a half minutes with 10 lsize and the result is still wrong , I wonder if the data set in your paper can be sent out for everyone to see

**Comment by miguelcastillon** [comment]
Added examples in the LNRR repository, please see there.
